### ISSUE TITLE
Test Dataverse Files / Accounts for MS Testing

### ISSUE THREAD

**Issue by raprasad** [privacytoolsproject/burdock#19]
### 1. Test Dataverse / Dataset
  - Set up a test Dataverse/Dataset* with files that may be downloaded/retrieved in tab-delimited format.  These files will have unique identifiers.  (* Within the Dataverse context, a Dataset is a collection of files.)

### 2. User accounts / tokens

- Create two user accounts and related tokens for the following purposes:
   - **Service Account** - This account will be used by the MSFT service to retrieve files via the Dataverse API.
    - **User Account** - This account will represent the researcher who:
      - Has permission to access a Dataverse and to browse lists of Dataset files
      - Cannot access the raw data, e.g. cannot download or retrieve the files.   
      - Cannot access summary statistics:  neither the DDI document produced by Dataverse ingest nor the R-created summary statistics.

**Comment by djbrooke** [comment]
Hey @raprasad, I added https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.70122/FK2/LLE0ES with two tabular files from one of Gary's datasets. I have not published yet but can do so. Let me know if there's other metadata I should add or files I should use here. 

Regarding the user accounts, how do you want to create them? Are there login types/credentials that  we should use, or should we let the respective teams/users create them and then set up the permissions?

**Comment by raprasad** [comment]
@eedeleon See Danny's note ^ regarding creation of Dataverse accounts (one to represent a service account and the other the user).

**Comment by eedeleon** [comment]
Thanks @raprasad , I created two dataverse accounts eedeleon and burdock. Can we have 2 datasets. 1 where both have access and 1 that only burdock has access to?

**Comment by djbrooke** [comment]
Hi @eedeleon - I've published the dataset so you should now have access:

https://demo.dataverse.org/dataset.xhtml?persistentId=doi%3A10.70122%2FFK2%2FLLE0ES

You can see one of the files in the dataset is restricted (adjacency_subset.tab) and one is not (allc_subset.tab). When you say you want one dataset do you mean file or dataset (a collection of files and related metadata)? Take a look at what's there and let me know if I should adjust anything.

**Comment by eedeleon** [comment]
Hi @djbrooke as expected, I was able to download one file but not the other from the python SDK.

import dataverse  # from the iqss python sdk
connection = dataverse.Connection(host, token)

# I got the files and download_urls with the SDK but could not download the private file

(Pdb) requests.get("https://demo.dataverse.org/api/v1/access/datafile/395812")
<Response [200]>
(Pdb) requests.get("https://demo.dataverse.org/api/v1/access/datafile/395811")
<Response [403]>
(Pdb) requests.get("https://demo.dataverse.org/api/v1/access/datafile/395811", auth=connection.auth)
<Response [403]>

I tried passing in the auth the same way the client does for the service document but was unsuccessful.

I am happy with 2 datasets in the same dataverse where I can download one private one from the burdock account but cannot download it from the eedeleon account. Currently I can download the open file so that is working perfectly.

Would giving the burdock account access to the restricted dataset make the returned download_url work for that account and not the other? If so, that would be the last step I would need to have a working example.
